name: Publish to Pip
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: upload
        uses: onichandame/pip-upload@master
        with:
          username: '__token__'
          password: ${{ secrets.PIP_PASSWORD }}
