name: Publish to Pip
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Test
        uses: onichandame/python-test-action@master
      - name: Upload
        uses: onichandame/pip-upload-action@0.0.1
        with:
          username: '__token__'
          password: ${{ secrets.PIP_PASSWORD }}
